
import java.awt.Dimension;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 2Ds_tec
 */
public class tela extends javax.swing.JFrame {
    private boolean lock = true;
    private static final int ETAPA_SENADOR = 0;
    private static final int ETAPA_GOVERNADOR = 1;
    private static final int ETAPA_PRESIDENTE = 2;
    private int etapaAtual = ETAPA_SENADOR;
    boolean votoValido = false;
    
    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
        photo.setPreferredSize(new Dimension(100,100));
        jpanelPhoto.setPreferredSize(new Dimension(100,100));
        pack();
        
        codes.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                verificarELoadFoto();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                verificarELoadFoto();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCodes = new javax.swing.JLabel();
        codes = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnRemake = new javax.swing.JButton();
        btnWhiteVote = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jpanelPhoto = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        labelVote = new javax.swing.JLabel();
        labelVote2 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelParty = new javax.swing.JLabel();
        nameParty = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        photo = new javax.swing.JLabel();
        labelCodes2 = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        labelHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 3, 0));
        setMaximumSize(new java.awt.Dimension(784, 285));

        labelCodes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCodes.setText("INSIRA O CÓDIGO DE DESBLOQUEIO");

        btn1.setBackground(new java.awt.Color(51, 51, 51));
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(51, 51, 51));
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(51, 51, 51));
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(51, 51, 51));
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(51, 51, 51));
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(51, 51, 51));
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(51, 51, 51));
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(51, 51, 51));
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(51, 51, 51));
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(51, 51, 51));
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnRemake.setBackground(new java.awt.Color(255, 153, 0));
        btnRemake.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnRemake.setText("CORRIGE");
        btnRemake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemakeActionPerformed(evt);
            }
        });

        btnWhiteVote.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnWhiteVote.setText("BRANCO");
        btnWhiteVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhiteVoteActionPerformed(evt);
            }
        });

        btnConfirm.setBackground(new java.awt.Color(51, 204, 0));
        btnConfirm.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnConfirm.setText("CONFIRMAR");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jpanelPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpanelPhotoLayout = new javax.swing.GroupLayout(jpanelPhoto);
        jpanelPhoto.setLayout(jpanelPhotoLayout);
        jpanelPhotoLayout.setHorizontalGroup(
            jpanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jpanelPhotoLayout.setVerticalGroup(
            jpanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelVote.setText("Seu voto vai para");

        labelVote2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelName.setText("Nome:");

        labelParty.setText("Partido:");

        nameParty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameParty.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labelCodes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnHelp.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        btnHelp.setText("Dicas");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        labelHelp.setText("<- Help");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelParty)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nameParty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(114, 114, 114))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(126, 126, 126))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelVote)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                                .addComponent(labelVote2)
                                                .addGap(195, 195, 195)))
                                        .addComponent(jpanelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelCodes, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(codes)
                                    .addComponent(labelCodes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelHelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWhiteVote, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm)
                    .addComponent(btnRemake, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWhiteVote, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemake, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelVote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelVote2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelName)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelParty)
                                    .addComponent(nameParty, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jpanelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCodes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCodes2)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void desbloquearUrna() {
    String codeKey = codes.getText();

    if (codeKey.equals("1509")) {
        lock = false;
        labelCodes.setText("Insira o número do candidato");
        codes.setText(""); 
        JOptionPane.showMessageDialog(this, "Urna desbloquada");
        etapaAtual = ETAPA_SENADOR;
        labelCodes2.setText("Senador(a) (3 dígitos)");
        labelHelp.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Código incorreto!");
        codes.setText("");
    }
}
    
    public void exibirFotoCandidato(String numeroCandidato) {
        String caminho = "Candidatos/" + numeroCandidato;
        
        try {
            URL imageUrl = getClass().getClassLoader().getResource(caminho);
            
            if (imageUrl != null) {
                ImageIcon originalIcon = new ImageIcon(imageUrl);
                
                int larguraLbl = photo.getWidth() > 0 ? photo.getWidth() : 100;
                int alturaLbl = photo.getHeight() > 0 ? photo.getHeight() : 100;
                
                Image scaledImage = originalIcon.getImage().getScaledInstance(larguraLbl, alturaLbl, Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(scaledImage);
                photo.setIcon(scaledIcon);
                photo.setText("");
            } else {
                photo.setIcon(null);
                photo.setText("Foto não encontrada");
                
                System.err.println("Imagem não encontrada: " + caminho);
            }
        } catch (Exception e) {
            photo.setIcon(null);
            photo.setText("Erro ao carregar foto");
        }
    }
    
    private void verificarELoadFoto() {
        String votoDigitado = codes.getText();
        
        switch(etapaAtual){
            case ETAPA_PRESIDENTE:
                if (votoDigitado.equals("13") && lock == false) {
                    exibirFotoCandidato("13.jpg");
                    name.setText("Luis Inácio Lula da Silva");
                    nameParty.setText("Partido dos Trabalhadores");
                    labelVote2.setText("Presidente");
                } else if (votoDigitado.equals("22") && lock == false) {
                    exibirFotoCandidato("22.jpg");
                    name.setText("Jair Messias Bolsonaro");
                    nameParty.setText("Partido Liberal");
                    labelVote2.setText("Presidente");
                } else {
                    photo.setIcon(null);
                    photo.setText("");
                    name.setText("");
                    nameParty.setText("");
                }
                break;
            case ETAPA_GOVERNADOR:
                if (votoDigitado.equals("30") && lock == false) {
                    exibirFotoCandidato("30.jpg");
                    name.setText("Romeu Zema");
                    nameParty.setText("Partido Novo");
                    labelVote2.setText("Governador");
                } else if (votoDigitado.equals("55") && lock == false) {
                    exibirFotoCandidato("55.jpg");
                    name.setText("Ratinho Júnior");
                    nameParty.setText("Partido Social Democrático");
                    labelVote2.setText("Govenador");
                } else if (votoDigitado.equals("15") && lock == false) {
                    exibirFotoCandidato("15.jpg");
                    name.setText("Helder Barbalho");
                    nameParty.setText("Movimento Democrático Brasileiro");
                    labelVote2.setText("Govenador");
                }  else {
                    photo.setIcon(null);
                    photo.setText("");
                    name.setText("");
                    nameParty.setText("");
                }
                break;
            case ETAPA_SENADOR: 
                if (votoDigitado.equals("222") && lock == false) {
                    exibirFotoCandidato("222.jpg");
                    name.setText("Marcos Pontes");
                    nameParty.setText("Partido Liberal");
                    labelVote2.setText("Senador");
                } else if (votoDigitado.equals("200") && lock == false) {
                    exibirFotoCandidato("200.jpg");
                    name.setText("Cleitinho Azevedo");
                    nameParty.setText("Republicanos");
                    labelVote2.setText("Senador");
                } else if (votoDigitado.equals("555") && lock == false) {
                    exibirFotoCandidato("555.jpg");
                    name.setText("Otto Alencar");
                    nameParty.setText("Partido Social Democrático");
                    labelVote2.setText("Senador"); 
                } else {
                    photo.setIcon(null);
                    photo.setText("");
                    name.setText("");
                    nameParty.setText("");
                }
                break;
        }
    }
    
    private void iniciarEtapa() {
        switch(etapaAtual) {
            case ETAPA_SENADOR:
                codes.setText("");
                labelVote2.setText("Senador(a)");
                break;
                case ETAPA_GOVERNADOR:
                labelCodes2.setText("Governador(a) (2 dígitos)");
                codes.setText("");
                labelVote2.setText("Governador(a)");
                labelHelp.setText("");
                break;
            case ETAPA_PRESIDENTE:
                labelCodes2.setText("Presidente (2 dígitos)");
                codes.setText("");
                labelVote2.setText("Presidente");
                labelHelp.setText("");
                break;
            default:
                labelCodes.setText("FIM DA VOTAÇÃO. Obrigado!");
                etapaAtual = 0;
                labelCodes2.setText("Urna bloqueada");
                labelHelp.setText("");
                codes.setText("");
                lock = true;
                break;
        }
        name.setText("");
        nameParty.setText("");
        photo.setIcon(null);
        photo.setText("");
        labelVote2.setText("");
    }
    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        codes.setText(codes.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        codes.setText(codes.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        codes.setText(codes.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        codes.setText(codes.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        codes.setText(codes.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        codes.setText(codes.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        codes.setText(codes.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        codes.setText(codes.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        codes.setText(codes.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        codes.setText(codes.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        if (lock) {
            desbloquearUrna();
            return;
        } 
        
        String voto = codes.getText();
        votoValido = false;
        String number = codes.getText();
        
        switch(etapaAtual){
            case ETAPA_SENADOR:
                if(number.equals("222") || number.equals("200") || number.equals("555")){
                    votoValido = voto.matches("\\d{3}");
                    break;
                };
            case ETAPA_GOVERNADOR:
                if(number.equals("15") || number.equals("30") || number.equals("55")){
                    votoValido = voto.matches("\\d{2}");
                    break;
                };
            case ETAPA_PRESIDENTE:
                if(number.equals("22") || number.equals("13")){
                    votoValido = voto.matches("\\d{2}");
                    break;
                };
        }
        
        if (!votoValido) {
            JOptionPane.showMessageDialog(this, "Número inválido para esta etapa!");
            codes.setText("");
            return;
        }
        
        etapaAtual++;
        iniciarEtapa();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnRemakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemakeActionPerformed
        codes.setText("");
    }//GEN-LAST:event_btnRemakeActionPerformed

    private void btnWhiteVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhiteVoteActionPerformed
        if (lock) {
            JOptionPane.showMessageDialog(this, "Desbloqueie a urna primeiro para votar");
            return;
        }
        
        etapaAtual++;
        iniciarEtapa();
        codes.setText("");
    }//GEN-LAST:event_btnWhiteVoteActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        if(lock == true) {
            labelHelp.setText("1509");
        } else {
            switch(etapaAtual) {
                case ETAPA_SENADOR:
                    labelHelp.setText("200 || 222 || 555");
                    break;
                case ETAPA_GOVERNADOR:
                    labelHelp.setText("15 || 30 || 55");
                    break;
                case ETAPA_PRESIDENTE:
                    labelHelp.setText("13 || 22");
                    break;
                default:
                    labelHelp.setText("");
                    break;
            }
        }
                
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnRemake;
    private javax.swing.JButton btnWhiteVote;
    private javax.swing.JTextField codes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpanelPhoto;
    private javax.swing.JLabel labelCodes;
    private javax.swing.JLabel labelCodes2;
    private javax.swing.JLabel labelHelp;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelParty;
    private javax.swing.JLabel labelVote;
    private javax.swing.JLabel labelVote2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameParty;
    private javax.swing.JLabel photo;
    // End of variables declaration//GEN-END:variables
}
